baseURL = 'https://scientic.space/'
languageCode = 'en-us'
title = 'Nishant Surya'
theme = 'PaperMod'
favicon = 'assets /favicon.ico'

[params]
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowShareButtons= true
    [params.homeInfoParams]
        Title = "Portfolio"
        Content = """Hi, I’m Nishant—a Computer Science graduate with a unique career in the life sciences and pharmaceutical industries. At TCS, I worked with clinical applications used in clinical trials like Medidata, JReview, and Oracle Clinical, ensuring software quality and creating user training resources to support clinical research professionals.

My experience in the pharma domain sparked a passion for crafting content that bridges technology and healthcare. As a freelance writer, I’ve expanded my expertise to include technical documentation, user guides, and medical content, such as articles on treatments, tests, and health-related topics.

With a strong foundation in clinical applications and writing, I specialize in simplifying complex concepts for healthcare, life sciences, and technology audiences."""
    
    
[assets]
    favicon16x16 = '/assets/favicon-16x16.png'
    favicon32x32 = '/assets/favicon-32x32.png'
    apple_touch_icon = '/assets/apple-touch-icon.png'
    android_chrome512x512 = '/assets/android-chrome-512x512'
    android_chrome192x192 = '/assets/android-chrome-192x192'

# [markup]
#   defaultMarkdownHandler = 'blackfriday'
#   [markup.blackFriday]
#     hrefTargetBlank = true

# [[menu.main]]
#   identifier = "categories"
#   name = "Categories"
#   url = "/categories/"
#   weight = 10

# [[menu.main]]
#   identifier = "tags"
#   name = "Tags"
#   url = "/tags/"
#   weight = 20


# [[menu.main]]
#   identifier = "archives"
#   name = "Archives"
#   url = "/archives/"
#   weight = 30

  [[menu.main]]
  identifier = "About"
  name = "About"
  url = "/about/"
  weight = 10

 #  [[menu.main]]
 # identifier = "Community"
 # name = "Community"
 # url = "/community/"
 # weight = 20


